module GaussianMarkovRandomFields

include("typedefs.jl")
include("utils/utils.jl")
include("linear_maps/linear_maps.jl")
include("preconditioners/preconditioners.jl")
include("gmrf.jl")
include("metagmrf.jl")
include("solvers/solvers.jl")
include("workspace/workspace.jl")
include("autoregressive/autoregressive.jl")
include("spdes/spdes.jl")
include("mesh/mesh.jl")
include("observation_models/observation_models.jl")
include("arithmetic/arithmetic.jl")
include("latent_models/latent_models.jl")
include("formula/constructors.jl")
include("plots/makie.jl")
include("kl_cholesky/base.jl")
include("graphical_lasso/graphical_lasso.jl")
include("workspace/gaussian_approximation.jl")
include("workspace/latent_model_integration.jl")
include("workspace/workspace_pool.jl")
include("autodiff/autodiff.jl")
include("workspace/autodiff.jl")

end
